### ISSUE TITLE
怎么使用postgresql

### ISSUE THREAD

**Issue by dodu2014** [xuejmnet/sharding-core#4]
我看示例中也没有postgresql的示例,希望补充一下, 最好完整的示例
另外使用方面, 照着官方文档处理, 有几处错误, 是不是类库已经更新, 文档没有更新

**Comment by xuejmnet** [comment]
收到,那个使用方面有错误的话方便吧错误信息发一下吗我这边解决一下。

**Comment by dodu2014** [comment]
这么快~~~
![image](https://user-images.githubusercontent.com/15245544/131205883-6f2572f4-ae75-444b-b4ba-2c1a36fe5c23.png)
第二个委托也是两个参数, 如果设置两个参数的话, 对于 op.UseShardingOptionsBuilder 而言, 传递同样的两个委托, 是不是可以优化成一个.

另外多处配置 .UseNpgsql(connectionString), 是不是也可以优化成1处呢.

**Comment by xuejmnet** [comment]
目前来讲没有办法优化成一个因为第二个委托的参数是字符串和builder，第一个委托必须是connection因为微软efcore官网有文档如果需要使多个dbcontext一起使用一个事务必须保证connection是同一个，但是后续或许可以优化成一个,目前你这个错误是第二个委托应该有两个参数不是一个参数,并且目前两个委托还能实现读写分离,所以暂时的计划是优化分页性能Thanks♪(･ω･)ﾉ

**Comment by xuejmnet** [comment]
dbcontext事务https://docs.microsoft.com/zh-cn/ef/core/saving/transactions,最开始写好的时候是只有一个的sqlserver下完美支持，因为sqlservver可以开启mars但是别的数据库不行所以就直接都按不支持multiallowresultsets=true来试用了

**Comment by dodu2014** [comment]
嗯, 那先不说优化的事, 文档示例中红线处暂时提示这个委托也必须是两个参数, 你可以先更新下文档 😊

**Comment by xuejmnet** [comment]
实在不好意思这边文档已更新 :)

**Comment by xuejmnet** [comment]
postgresql 和其他数据库后续我这边会出相应的demo的如果需要使用可以参考sqlserver或者mysql因为涉及到数据库的地方只有配置这一块其他地方没有使用数据库相关的所以原则上都是支持的 :)

**Comment by dodu2014** [comment]
谢谢, 希望没有给你带来打扰 😊
我们正在考虑efcore方面分表方案呢, 本来考虑netcore.sharding, 前天看到你的文章, 就体验一下先, 体验中或多或少可能会遇到一些问题, 所以可能会向你咨询. 😉

**Comment by xuejmnet** [comment]
这是我的荣幸

**Comment by xuejmnet** [comment]
如果我长时间没回复你可以加群我会回答的毕竟国内github有时候会抽疯

**Comment by dodu2014** [comment]
好的, 谢谢~~ 那就关闭了
