### ISSUE TITLE
自动也分表了，提交数据时出错

### ISSUE THREAD

**Issue by dodu2014** [xuejmnet/sharding-core#5]
用的AbstractSimpleShardingWeekKeyLongVirtualTableRoute路由：
![image](https://user-images.githubusercontent.com/15245544/131236740-e11ddb0f-d396-4293-aeba-84093105f84c.png)
也自动创建了表：
![image](https://user-images.githubusercontent.com/15245544/131236758-13319a79-4b5a-4e5c-8033-1f5fce20efd4.png)
写入数据，保存时出现异常：
![image](https://user-images.githubusercontent.com/15245544/131236778-c01f5f3d-5fc1-4632-afb4-22a7f9add93a.png)

我这个实体与其他表实体不存在数据关系引用

请教一下是我哪弄的不正确吗？

**Comment by dodu2014** [comment]
我的应用是车辆gps定位，这个表数据量比较大，亿级数据，想应用分表来解决查询性能

**Comment by xuejmnet** [comment]
数据库实体能给我看下嘛或者说你的db是什么能给我看看吗因为这个错误貌似不是我这边抛出的

**Comment by xuejmnet** [comment]
我看了貌似是Postgresql说你的GeoLocation不存在这张表

**Comment by xuejmnet** [comment]
是不是你插入的时候用的是自己的dbcontext
而不是继承abstractshardingdbcontext的那个dbcontext

**Comment by xuejmnet** [comment]
普通的dbcontext确实映射到了GeoLocation只有用AbstractShardingDbContext才会将映射关系改成分表的那个，所以我猜测是不是你的db.savechange的db用的不是分表的db

**Comment by dodu2014** [comment]
这个过程中，还有其他未使用分表的数据更新，直接使用shardingdb也可以是吗？

**Comment by dodu2014** [comment]
![image](https://user-images.githubusercontent.com/15245544/131236906-8731057d-5afe-45f5-9c9b-779782a50e80.png)
这是数据实体

**Comment by xuejmnet** [comment]
ShardingDbContext内部支持分表和未分表的一起操作,对了有个问题可能我没说清楚就是一切按时间来的路由如果重写了GetBeginTime，这个方法必须返回静态值,因为如果你下次程序启动这个动态值就会不对了

**Comment by dodu2014** [comment]
我把其他相关的内容也截图给你

shardingdb：
![image](https://user-images.githubusercontent.com/15245544/131236947-86d476c6-31ff-497b-b44b-510f3a91175a.png)

table map：
![image](https://user-images.githubusercontent.com/15245544/131236961-13e675fb-c1b5-40c2-93df-9d1ec0c8dc8d.png)

**Comment by dodu2014** [comment]
> ShardingDbContext内部支持分表和未分表的一起操作,对了有个问题可能我没说清楚就是一切按时间来的路由如果重写了GetBeginTime，这个方法必须返回静态值,因为如果你下次程序启动这个动态值就会不对了

嗯好，也就是返回一个初始化日期，最好是比较早的日期是吧

**Comment by xuejmnet** [comment]
如果需要ShardingDbContext内部支持未分表需要将未分表也配置到dbcontext里面,对了还有就是初始化日期不一定是比较早的值，如果是过早的值会导致你需要建立很多张表,你可以理解为如果我打算从今天开始建表如果是按周的就在本周内的任意时间都可以,如果你返回去年的时间,程序会在启动的时候和当前时间进行计算建立beginTime到现在的表,如果你是按天的就会建立一年的表300多张,这样其实是没有意义的反而没必要

**Comment by xuejmnet** [comment]
对了还有一点如果是按时间点来的话需要自己写定时任务添加到分表或者创建表具体demo里面有的可以做参考

**Comment by dodu2014** [comment]
我是想按周分表呢，1周可能就千万级数据了

**Comment by xuejmnet** [comment]
这个是一样的按天还是按周,你可以在如果按周你在每周日晚上23点调用demo的动态建表就可以了,当然也可以提早比如周5就建好了也是可以的
```c#

        [JobRun(Name = "定时创建分表组件", Cron = "0 0 12 * * ?", RunOnceOnStart = true)]

        public void AutoCreateTable(IVirtualTableManager virtualTableManager, IShardingTableCreator tableCreator)
        {
            var virtualTable = virtualTableManager.GetVirtualTable<DefaultShardingDbContext, SysUserLogByDay>();
            if (virtualTable == null)
            {
                return;
            }
            var now = DateTime.Now.Date.AddDays(1);
            var tail = virtualTable.GetVirtualRoute().ShardingKeyToTail(now);
            try
            {
                virtualTableManager.AddPhysicTable<DefaultShardingDbContext>(virtualTable, new DefaultPhysicTable(virtualTable, tail));
                tableCreator.CreateTable<DefaultShardingDbContext, SysUserLogByDay>(tail);
            }
            catch (Exception e)
            {
                //ignore
            }
        }
```
代码的意思很明白了,就是传入对应时间返回给你应该是什么后缀你就按这个后缀加入当前物理表,并且调用建表接口,建表接口会帮你自动建表

**Comment by xuejmnet** [comment]
查询的时候最好带上那个时间这样就可以精确到某一张表了性能可以提升很多

**Comment by dodu2014** [comment]
好的👌🏻 谢谢，非常感谢，我下午回去再试试

**Comment by dodu2014** [comment]
现在已经解决了上午的问题, 是使用了原来的dbcontext, 现在改用了 shardingdb 来提交持久化,
遇到了新的问题:
Unable to cast object of type 'System.DateTime' to type 'System.Int64'.
![image](https://user-images.githubusercontent.com/15245544/131242607-3dc83850-1633-415d-969a-277ec9898bd5.png)

**Comment by dodu2014** [comment]
![image](https://user-images.githubusercontent.com/15245544/131242633-5a13681f-2b6b-4786-9887-ba1ddbaa7004.png)

路由已经返回了固定值

**Comment by xuejmnet** [comment]
![image](https://user-images.githubusercontent.com/18061232/131242740-ed5cd410-3255-4770-92be-3ea07903ea88.png)
选择正确的路由如果是使用默认的目前提供了timestamp和datetime两种类型
