### ISSUE TITLE
Abp下同时使用插入未分表和分表

### ISSUE THREAD

**Issue by chaoyi996** [xuejmnet/sharding-core#72]
感谢您为开源生态做出的贡献，
在使用Abp+本库时，遇到一些问题，特来请教。

1. 表A外键关联至表B
2. 在同一个UOW下，先创建表B的一条数据，再创建表A的一条数据
3. 有一定的几率创建成功，更多的时候会爆出外键冲突的错误，
4. 个人推测是因为保存的时候先保存了表A，这时候表B的对应数据还不存在，所以报错。

特来请教，感谢。

**Comment by xuejmnet** [comment]
您这边是子表和主表，然后子表采用的是分表，并且子表拥有外加约束到主表是吗，这种情况下目前有两个解决方案

1.移除子表外键约束，可以通过移除外键的code first实现
2.可以通过开启事务然后插入主表之后savechange然后inset子表然后savechange然后commit transaction

**Comment by xuejmnet** [comment]
[移除外键的方法](https://github.com/xuejmnet/sharding-core/blob/main/samples/Sample.Migrations/RemoveForeignKeyMigrationsModelDiffer.cs)
当然基于您这种情况应该是在dbcontext进行提交的时候出现了先后提交乱序的一个bug，这边我发布一个版本可以针对您这种看下进行处理

**Comment by xuejmnet** [comment]
您好我这边已经发布了最新版本x.3.1.53，已经将未分表的dbcontext提交至最前，可以解决您现在这种情况的发生

**Comment by chaoyi996** [comment]
十分感谢，我稍后测试一下。

**Comment by chaoyi996** [comment]
再次感谢您对.Net开源做出的贡献

**Comment by xuejmnet** [comment]
请问您的问题是否已经解决了 : )

**Comment by chaoyi996** [comment]
问题已解决，十分感谢
