### ISSUE TITLE
与abp VNext使用的疑问

### ISSUE THREAD

**Issue by chaoyi996** [xuejmnet/sharding-core#80]
作者您好，我在使用时Abp Vnext+本库时，发现如果实体继承AggregateRoot<>（即实现了IHasConcurrencyStamp接口），在更新本实体时候会出现死循环，会一直更新ConcurrencyStamp字段，特来请教，多谢

**Comment by xuejmnet** [comment]
不好意思不知道什么原因我没收到对应的通知,这么久才看到你的问题,"会一直更新ConcurrencyStamp字段"具体是指什么能说下嘛

**Comment by xuejmnet** [comment]
![image](https://user-images.githubusercontent.com/18061232/146133369-7802e57e-79b7-4bca-8ffb-1e84dbaa7e65.png)
我这边测试了是ok的不知道你说的什么问题不能修改还是什么[AbpVNextToApp](https://github.com/xuejmnet/AbpVNextShardingTodoApp/blob/main/src/TodoApp.Application/TodoAppService.cs)具体你可以拉一下代码看看

**Comment by xuejmnet** [comment]
@chaoyi996 或者最好可以提供一下具体的情况或者错误可能是我理解错误了

**Comment by chaoyi996** [comment]
感谢您，可能是我的其他代码对此有干扰。我将对此重新进行测试，有测试结果反馈给您。十分感谢

**Comment by xuejmnet** [comment]
@chaoyi996 没事这是我应该做的,感谢您一直关注本库 ：）

**Comment by chaoyi996** [comment]
作者您好，我在进行测试时发现以下情况：
1.下载AbpVNextShardingTodoApp代码，使用新数据库，运行TodoApp.DbMigrator程序进行数据迁移，提示以下错误
![image](https://user-images.githubusercontent.com/14135714/146168357-5fd6bbe3-cd40-4f6f-9852-bf44fbcae882.png)
2.使用其他Abp项目对新数据库进行迁移，保证数据库中有正常数据。使用AbpVNextShardingTodoApp项目进行Update操作，此时TodoItems等表可自动创建，使用AbpVNextShardingTodoApp自带的页面进行查询和插入，正常。
-上述结论，在使用AbstractShardingAbpDbContext时，无法使用Abp的数据迁移功能，update-database指令正常工作，推测和种子数据有关（导航属性）。
3.将2中测试正常的程序进行升级，Abp升级至4.4.4、ShardingCore升级至5.3.1.82，功能正常，其余测试正在进行。

**Comment by xuejmnet** [comment]
@chaoyi996 迁移请将项目启动项和nuget控制台设置为控制台那个，之后可以正常使用uodate-database和add mi

**Comment by chaoyi996** [comment]
这里我使用的是TodoApp.DbMigrator的Console程序，运行这个程序可以自动进行种子数据的迁移。

**Comment by chaoyi996** [comment]
使用update-database命令可正常创建数据库，但缺失种子数据。

**Comment by xuejmnet** [comment]
@chaoyi996 生成脚本看一下是否有种子数据

**Comment by chaoyi996** [comment]
使用add-migration生成的脚本没有种子数据，种子数据是TodoApp.DbMigrator的程序进行添加的

**Comment by xuejmnet** [comment]
@chaoyi996  能否看下相关代码

**Comment by chaoyi996** [comment]
不好意思没能明白您是指哪些代码，我没有在TodoApp.DbMigrator添加种子数据，但Abp有一些默认的种子数据，如Admin用户和Admin角色。

**Comment by xuejmnet** [comment]
你指的是abp的默认种子数据是吗，你这边能确定abp的有对应的种子数据吗，如果有的我去下载一个原始的abp todoitem来进行测试看看

**Comment by chaoyi996** [comment]
确认Abp有自带的种子数据。
目前我个人推测是因为种子数据导致的TodoApp.DbMigrator执行异常，因为update-database命令可正常执行。
十分感谢。

**Comment by xuejmnet** [comment]
@chaoyi996 好的我这边看下，还有你说的并发字段死循环是什么情况处理完成了吗

**Comment by chaoyi996** [comment]
正在基于您提供的AbpVNextShardingTodoApp项目进行测试。

**Comment by xuejmnet** [comment]
@chaoyi996 是在不好意思我这边测试了[abp的原生例子](https://github.com/abpframework/abp-samples/tree/master/TodoApp/Mvc-EfCore) 进行迁移并没有发现有种子数据添加你这边可以说一下具体是在哪边添加的嘛因为我好想代码里面和初始化的种子文件里面都没有看到诶

**Comment by xuejmnet** [comment]
@chaoyi996 我这边尝试了2次并没有发现Abp的ToItem附带了任何种子数据,并不是和你说的那样初始化有种子数据

**Comment by xuejmnet** [comment]
@chaoyi996 你是通过启动TodoApp.DbMigrator这个项目还是说仅仅只是通过nuget命令update-database

**Comment by chaoyi996** [comment]
您好，TodoItem没有种子数据，种子数据只在运行TodoApp.DbMigrator时被添加，执行update-database命令不会添加。
目前我测试执行update-database没有异常，可创建表结构。运行TodoApp.DbMigrator出错。
所以我个人推测是因为种子数据导致的异常

>

**Comment by xuejmnet** [comment]
@chaoyi996  只需要将TodoAppDbContext上的`[ReplaceDbContext(typeof(IIdentityDbContext))]`去掉即可

**Comment by chaoyi996** [comment]
您好，经过您的指点，迁移问题已解决，ConcurrencyStamp循环的问题未重现，可能是项目其他代码导致，现在有个新的问题请教您：
结合Abp，分表后是否会导致Abp的AutoSave（或工作单元）失效？
如下图，先进行插入并AutoSave，后马上进行查询，在查询结果内没有找到刚插入的数据。
![image](https://user-images.githubusercontent.com/14135714/146187043-19797465-b4e1-4a01-b7b9-e90ff725d53d.png)

下图是原生ToDoApp的测试结果，可以正常查询到刚刚插入的数据
![image](https://user-images.githubusercontent.com/14135714/146188125-d5ab17c1-12ea-4f90-8234-70f24095a9e3.png)

下图是Abp关于AutoSave的源码，似乎就是执行了SaveChangesAsyn
![image](https://user-images.githubusercontent.com/14135714/146188898-c00a1754-029f-4941-8b3b-b29e87571e33.png)

**Comment by xuejmnet** [comment]
@chaoyi996 因为abp这个autosave其实只是提交上去了，但是因为外部是开事务的所以其实并没有插入到数据库，又因为你的本次查询是查询多个表所以是没有办法查询到数据的因为当涉及到多表查询的时候会进行多个dbconnection查询没有正真插入的数据是无法被查询到的[我已经在这边有了对应的说明](https://github.com/xuejmnet/sharding-core/issues/41)，当然除非你使用主键查询是可以被查询到的,但是因为我比较懒,这边abp的分表例子用的是分表字段为string的路由实际是guid所以安主键查询会报错，改成guid的路由就可以了

**Comment by chaoyi996** [comment]
明白了，十分感谢

**Comment by xuejmnet** [comment]
这边的涉及一张表指的是同一个对象是否跨表了，只要是同一个对象没有跨表就会复用原先的dbconnection并且每次都是同一个dbconnection

**Comment by xuejmnet** [comment]
![image](https://user-images.githubusercontent.com/18061232/146191604-720f2508-41c3-41f5-8afe-21582b80827a.png)
具体源码可以参考这边

**Comment by chaoyi996** [comment]
明白了，我再学习一下，十分感谢您的指点。
