### ISSUE TITLE
和ABP结合使用

### ISSUE THREAD

**Issue by DrZhong** [xuejmnet/sharding-core#87]
说好的 “零业务代码入侵”的呢，为什么还要封装 services.AddShardingDbContext，那么问题来了 abp也对 AddDbContext 进行了封装。请问这里如何做到 “零业务代码入侵”，如图：
![image](https://user-images.githubusercontent.com/8085571/147433265-c8a84548-71af-41ce-8221-7bad15226a30.png)

**Comment by xuejmnet** [comment]
您好很高兴能看到你对本框架的关注
![image](https://user-images.githubusercontent.com/18061232/147448477-6a0ad419-89f9-4aa2-acc1-e9e1bd1b8385.png)

https://github.com/xuejmnet/AbpVNextShardingTodoApp/blob/main/src/TodoApp.EntityFrameworkCore/EntityFrameworkCore/TodoAppEntityFrameworkCoreModule.cs

**Comment by xuejmnet** [comment]
ShardingCore的Startup`services.AddShardingDbContext`这部分的代码是封装了AddDbContext和AddShardingConfigure,如果你的AddDbContext是已经被别的框架封装了也没事的只需要额外添加AddShardingConfigure即可,简单来说就是`AddShardingDbContext`是`AddDbContext`+`AddShardingConfigure`

**Comment by xuejmnet** [comment]
@DrZhong 具体可以参考文档一个是abp的demo一个是abpvnext继承的博客 https://xuejm.gitee.io/sharding-core-doc/abp/

**Comment by xuejmnet** [comment]
![image](https://user-images.githubusercontent.com/18061232/147448929-f637c05a-47a0-4bc0-aabb-0069235f6d99.png)

**Comment by DrZhong** [comment]
> @DrZhong 具体可以参考文档一个是abp的demo一个是abpvnext继承的博客 https://xuejm.gitee.io/sharding-core-doc/abp/

嗯嗯，刚接触没有深入去看，已经看到了，谢谢
