### ISSUE TITLE
在group by 语句中 使用FirstOrDefaultAsync取出最近一条数据，出错

### ISSUE THREAD

**Issue by chaoyi996** [xuejmnet/sharding-core#94]
作者您好，在使用本框架时有些问题，特来请教，
业务：有一个设备用电历史记录表，需要在表中查询出每个设备最近一次用电情况，表结构如下：
![image](https://user-images.githubusercontent.com/14135714/148649401-c15cc5db-2e1d-41e1-a134-a20eaabbc7f7.png)
使用伪代码：
` var lastDatas = (await _energyDataRepository.GetQueryableAsNoTrackingAsync())
                                    .Where(i =>
                                        i.DataTime < g.Key && deviceIds.Contains(i.DeviceId))
                                    .GroupBy(i => new { i.DeviceId }, i => i, (i, u) =>
                                        new { Data = u.OrderByDescending(x => x.DataTime).FirstOrDefault() }).ToList();`
发现问题：如果在where中 手动指定一个月的时间范围（即，不让程序分表查询）此时一切正常。
如果不指定一个月的时间范围，出现分表查询的情况，会报出null的异常。

**Comment by chaoyi996** [comment]
分表粒度：按年月分表

**Comment by xuejmnet** [comment]
您好我这边可以的话最好能够发一下错误堆栈，我这试试还有您使用的是x.3.2.10是吧

**Comment by xuejmnet** [comment]
实在不好意思我这边看了确实是sjarding core这边的问题我这边也看了，目前这么复杂的group shardingcore还不支持，您可能只能通过foreach迭代月份来实现单月的处理了，内存聚合。后续我会进行支持目前来说没那么快支持

**Comment by xuejmnet** [comment]
@chaoyi996 
```c#

            var ids = new List<string>(){ "200", "300" };
            List<SysUserSalary> result = new List<SysUserSalary>(ids.Count);
            var routeFilter = new List<SysUserSalary>().AsQueryable().Where(o => ids.Contains(o.UserId));
            //获取的路由时间倒序
            var tableRouteResults = _tableRouteRuleEngineFactory.Route(routeFilter)
                .Select(o => o.ReplaceTables.First().Tail).OrderByDescending(o => o).ToList();
            foreach (var tableRouteResult in tableRouteResults)
            {
                if(ids.IsEmpty())
                    break;
                using (_shardingRouteManager.CreateScope())
                {
                    _shardingRouteManager.Current.TryCreateOrAddMustTail<SysUserSalary>(tableRouteResult);
                    var queryable = _virtualDbContext.Set<SysUserSalary>().Where(o => ids.Contains(o.UserId))
                        .GroupBy(o => new { o.UserId }, i => i,
                            (i, u) => new {
                                Data = u.OrderByDescending(o => o.DateOfMonth).FirstOrDefault()
                            });
                    var r =await queryable.ToListAsync();
                    result.AddRange(r.Select(o=>o.Data));
                    var removeUserIds = result.Select(u => u.UserId).ToHashSet();
                    ids.RemoveAll(o => removeUserIds.Contains(o));
                }
            }
```
主要依赖注入有两个`IShardingRouteManager`和`ITableRouteRuleEngineFactory<ShardingDefaultDbContext>`,先根据表达式获取当前路由因为只有一个对象所以ReplaceTables里面直接获取first然后通过强制路由挨个处理,但是必须开启提示路由

```c#

    public class SysUserSalaryVirtualTableRoute:AbstractSimpleShardingMonthKeyDateTimeVirtualTableRoute<SysUserSalary> 
    {
        protected override bool EnableHintRoute =>true;//开启提示路由
     }
```

**Comment by chaoyi996** [comment]
不好意思刚刚收到邮件。
非常感谢，我将学习尝试您的示例。
